on: [pull_request]

name: wasm-pack

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install wasm-pack
        run: cargo binstall wasm-pack --version 0.14.0 --no-confirm --force

      - name: Test on Chrome
        run: PATH="$HOME/.cargo/bin:$PATH" wasm-pack test --headless --chrome --all-features

      - name: Test on Firefox
        run: PATH="$HOME/.cargo/bin:$PATH" wasm-pack test --headless --firefox --all-features

  build-size:
    name: Build size limit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install wasm-pack
        run: cargo binstall wasm-pack --version 0.14.0 --no-confirm --force

      - name: Assert bundle size (gzipped)
        run: PATH="$HOME/.cargo/bin:$PATH" make test-wasm-size
